FROM python:3.7-alpine
RUN apk update && \
    apk add --no-cache gcc musl-dev linux-headers && \
    apk add postgresql-dev libffi-dev g++ make libressl-dev

COPY ./all-requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
