"""empty message

Revision ID: v0.0.3
Revises: 
Create Date: 2020-10-20 13:57:55.728947

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "v0.0.3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.String(length=67), nullable=True),
        sa.Column("endpoint_id", sa.String(length=67), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=True),
        sa.Column("globus_identity", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("namespace", sa.String(length=1024), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "containers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author", sa.Integer(), nullable=True),
        sa.Column("container_uuid", sa.String(length=67), nullable=True),
        sa.Column("name", sa.String(length=1024), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "functions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=1024), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=1024), nullable=True),
        sa.Column("function_name", sa.String(length=1024), nullable=True),
        sa.Column("function_uuid", sa.String(length=38), nullable=True),
        sa.Column("function_source_code", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("entry_point", sa.String(length=38), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("public", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("function_uuid", name="unique_function_uuid"),
    )
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=True),
        sa.Column("endpoint_name", sa.String(length=256), nullable=True),
        sa.Column("endpoint_uuid", sa.String(length=38), nullable=True),
        sa.Column("public", sa.Boolean(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("ip_addr", sa.String(length=15), nullable=True),
        sa.Column("city", sa.String(length=256), nullable=True),
        sa.Column("region", sa.String(length=256), nullable=True),
        sa.Column("country", sa.String(length=256), nullable=True),
        sa.Column("zipcode", sa.String(length=10), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("core_hours", sa.Float(), nullable=True),
        sa.Column("hostname", sa.String(length=256), nullable=True),
        sa.Column("org", sa.String(length=256), nullable=True),
        sa.Column("restricted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint_uuid", name="unique_endpoint_uuid"),
    )
    op.create_table(
        "container_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("container_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=256), nullable=True),
        sa.Column("location", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["container_id"],
            ["containers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "function_auth_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("function_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["functions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["auth_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "function_containers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("container_id", sa.Integer(), nullable=True),
        sa.Column("function_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["container_id"],
            ["containers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["functions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "restricted_endpoint_functions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=True),
        sa.Column("function_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["sites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["functions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("task_uuid", sa.String(length=38), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("endpoint_id", sa.String(length=38), nullable=True),
        sa.Column("function_id", sa.String(length=38), nullable=True),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["sites.endpoint_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["functions.function_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("restricted_endpoint_functions")
    op.drop_table("function_containers")
    op.drop_table("function_auth_groups")
    op.drop_table("container_images")
    op.drop_table("sites")
    op.drop_table("functions")
    op.drop_table("containers")
    op.drop_table("users")
    op.drop_table("auth_groups")
    # ### end Alembic commands ###
